# NumPy

# numpy

In [1]:
import numpy as np

In [3]:
n1 = np.array([10,20,30,40])

In [4]:
n1

array([10, 20, 30, 40])

In [5]:
type(n1)

numpy.ndarray

In [7]:
n2 = np.array([[1,2,3,4],[4,3,2,1]])

In [8]:
n2

array([[1, 2, 3, 4],
       [4, 3, 2, 1]])

# np.zeros

In [11]:
n3 = np.zeros((1,2))
n3

array([[0., 0.]])

# np.full

In [14]:
n1 = np.full((5,5),6)
n1

array([[6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6]])

In [12]:
n2 = np.zeros((3,3))
n2

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

#  np.arange

In [16]:
n2 = np.arange(10,20)
n2

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [18]:
n1 = np.arange(10,100,5)
n1

array([10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90,
       95])

# np.random.randint

In [25]:
n2 = np.random.randint(10,100,5)
n2

array([47, 45, 35, 26, 38])

# shape

In [23]:
n3.shape

(1, 2)

In [26]:
n2.shape

(5,)

In [27]:
n4 = np.array([[1,2,3,4],[4,3,2,1]])
n4.shape


(2, 4)

In [28]:
n4.shape = (4,2)
n4

array([[1, 2],
       [3, 4],
       [4, 3],
       [2, 1]])

# joining numpy arrays

In [41]:
n1 = np.array([1,2,3,0])
n2 = np.array([4,5,6,7])


In [42]:
np.vstack((n1,n2))


array([[1, 2, 3, 0],
       [4, 5, 6, 7]])

In [43]:
np.vstack((n2,n1))

array([[4, 5, 6, 7],
       [1, 2, 3, 0]])

In [44]:
np.hstack((n1,n2))

array([1, 2, 3, 0, 4, 5, 6, 7])

In [45]:
np.column_stack((n1,n2))

array([[1, 4],
       [2, 5],
       [3, 6],
       [0, 7]])

In [46]:
np.column_stack((n2,n1))

array([[4, 1],
       [5, 2],
       [6, 3],
       [7, 0]])

# numpy intersection and difference

In [52]:
n1 = np.array([10,20,30,40,60])
n2 = np.array([50,60,70,80,90])

In [53]:
np.intersect1d(n1,n2)

array([60])

In [54]:
np.setdiff1d(n1,n2)

array([10, 20, 30, 40])

In [55]:
np.setdiff1d(n2,n1)

array([50, 70, 80, 90])

# numpy mathematics

In [56]:
n1 = np.array([10,20])
n2 = np.array([30,40]) 

In [58]:
np.sum((n1,n2))

100

In [59]:
np.sum([n1,n2],axis=0)

array([40, 60])

In [60]:
np.sum([n1,n2],axis=1)

array([30, 70])

In [63]:
n1 = np.array([10,20,30])
n1 = n1 + 5
n1

array([15, 25, 35])

In [65]:
n1 = n1 - 5
n1

array([ 5, 15, 25])

In [66]:
n1 * 10

array([ 50, 150, 250])

In [67]:
n1 / 5

array([1., 3., 5.])

In [68]:
np.mean(n1)

15.0

In [70]:
n2 =  np.array([5,8,6,9])
np.mean(n2)

7.0

In [71]:
np.std(n2)

1.5811388300841898

# numpy matrix

In [73]:
n1 =  np.array([[1,2,3],[4,5,6],[7,8,9]])
n1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [74]:
n1[0]

array([1, 2, 3])

In [76]:
n1[:,1]

array([2, 5, 8])

In [77]:
n1[:,2]

array([3, 6, 9])

In [78]:
n1[:,0]

array([1, 4, 7])

In [80]:
n1[:,1]

array([2, 5, 8])

In [81]:
n1.transpose()

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

# matrix multiplication

In [86]:
n1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [83]:
n2 = n1.transpose()
n2

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [84]:
n1.dot(n2)

array([[ 14,  32,  50],
       [ 32,  77, 122],
       [ 50, 122, 194]])

In [85]:
n2.dot(n1)

array([[ 66,  78,  90],
       [ 78,  93, 108],
       [ 90, 108, 126]])

In [91]:
n1 = np.array([10,20,30,40,50])
np.save('save_n1',n1)

In [92]:
n2 = np.load('save_n1.npy')
n2

array([10, 20, 30, 40, 50])